builders:
  json_config_generator:
    target: ":json_config_annotations"
    import: "package:json_config_generator/json_config_generator.dart"
    builder_factories: ["configBuilder"]
    build_extensions: { ".dart": [".json_config_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
