name: json_config_generator
description: Configuration generator from json files.
version: 0.1.0
homepage: https://dev.azure.com/fcorp-infraestructura-servicios-ti/Packages/_git/Flutter.ConfigGenerator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.4.0
  build: ^2.1.1
  dart_style: ^2.2.0
  source_gen: ^1.1.1
  code_builder: ^4.1.0
  build_config: ^1.0.0
  built_collection: ^5.1.1
  json_config_annotation: ^0.1.0
  recase: ^4.0.0

dev_dependencies:
